#! /usr/bin/env python_sqlite

import os, time, sys, traceback
f = open('/afs/cern.ch/user/l/larcomm/w0/digitMon/output/logs/cron.log', 'a')
f.write('cafMgr_run running at ' + time.asctime() + '\n')

try:
  import CAFInterface
  CAFInterface.run(sys.argv)
except Exception, inst :
  f.write('cafMgr_run failed with exception ' + str(inst) + '\n')
  error_type, error_value, trbk = sys.exc_info()
  traceback.print_tb(trbk, None, f)

f.close()

